### ISSUE TITLE
[Enhancement] Let users know when there's an available presence on store for the page we are in

### ISSUE THREAD

**Issue by Jorc0** [PreMiD/PreMiD#843] opened 2022-05-03 13:50 UTC
**Is your feature request related to a problem? Please describe.**
It would be nice the extension to put a red icon above the premid icon to make us know theres an available presence for the current webpage we are in

**Describe the solution you'd like**

![imagen_2022-05-03_154816770](https://user-images.githubusercontent.com/48130077/166466378-d869c13a-e9b8-4b7e-876a-20982423aff5.png)

**Comment by EncryptedDev** [comment] 2022-05-13 21:18
Hello @Jorc0 👋

This is a planned feature for PreMiD V3

**Comment by EncryptedDev** [comment] 2022-05-13 21:59
Duplicate of PreMiD/Extension#13

**Closed by EncryptedDev** 2022-05-13 21:59 UTC
Labels: enhancement
