### ISSUE TITLE
Feature: Hide presence when tab is not used

### ISSUE THREAD

**Issue by eDexiam** [PreMiD/PreMiD#794] opened 2021-12-22 10:34 UTC
**Idea/Problem**
I use a lot of tabs in my browser and I don't always tend to close those that I don't use in the moment, so when I go another website that does not have PreMiD support or don't use my browser actively the presence stays.

**Solution**
Presences should be hidden if the associated tab is not focused.
As for not using the browser an inactivity timer could be set (Preferably configurable). So if you don't interact with the page where the presence originates from it would stop displaying it after a while.

**Comment by EncryptedDev** [comment] 2022-05-13 21:35
We could think about adding this as a setting in V3

**Comment by EncryptedDev** [comment] 2022-05-13 22:00
Duplicate of PreMiD/Extension#36

**Closed by EncryptedDev** 2022-05-13 22:00 UTC

**Comment by SeerLite** [comment] 2025-02-15 05:47
Hi, was this ever implemented? I looked at all linked issues and found no link to any commit or PR and I can't find anything in the settings.
