### ISSUE TITLE
Does not launch on Mac

### ISSUE THREAD

**Issue by austinhuang0131** [PreMiD/PreMiD#248] opened 2019-10-17 17:26 UTC
Edit: Fixed by restarting Chrome but like it's still an issue

---

**Describe the bug**
Can't launch the app, with error.

**To Reproduce**
1. Download from your site
2. Click to install
3. PreMiD will ask for permissions, but regardless of allow or deny it'll quit with the error message below

**Expected behavior**
The app launches

**Screenshots**

Error message:
```
TypeError: Cannot read property 'emit' of undefined
    at process.<anonymous> (/Applications/PreMiD/PreMiD.app/Contents/Resources/app/index.js:32:28)
    at process.emit (events.js:200:13)
    at processPromiseRejections (internal/process/promises.js:165:18)
    at processTicksAndRejections (internal/process/task_queues.js:90:32)
```

Console errors (message type:error, message type:fault, any:premid)
```
error	13:21:46.007797 -0400	PreMiD	        AEGetDescData of non-desc type 'reco' not a good idea
error	13:21:46.046696 -0400	PreMiD	nw_path_close_fd Failed to close guarded necp fd 33 [9: Bad file descriptor]
error	13:21:46.070370 -0400	PreMiD	nw_path_close_fd Failed to close guarded necp fd 33 [9: Bad file descriptor]
error	13:21:46.242067 -0400	tccd	Failed to copy signing info for 15731, responsible for file:///Applications/PreMiD/PreMiD.app/Contents/MacOS/PreMiD: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)"
error	13:21:51.225458 -0400	tccd	Failed to copy signing info for 15731, responsible for file:///Applications/PreMiD/PreMiD.app/Contents/MacOS/PreMiD: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)"
error	13:21:52.139731 -0400	sandboxd	Sandbox: defaults(15749) System Policy: deny(1) file-read-data /Users/austinhuang/Library/Containers/com.apple.VoiceMemos/Data/Library/Preferences
Violation:       System Policy: deny(1) file-read-data /Users/austinhuang/Library/Containers/com.apple.VoiceMemos/Data/Library/Preferences 
<...>
Responsible:     /Applications/PreMiD/PreMiD.app/Contents/MacOS/PreMiD [15731]
<...>
```

**Desktop (please complete the following information):**
 - OS: Mac Mojave 10.14.6

**Additional context**
Application did successfully run at first install, but afterwards it's having problems. Attempted deleting respective application support folder, multiple uninstalls, giving permissions, etc. Computer has node.js

**Comment by WOZARDLOZARD** [comment] 2019-10-18 22:50
My app was also running fine when I first installed it and I was using it for a few days, but I got the same issue here. Restarting Chrome didn't fix it for me, so I think this will be addressed sometime in a future update. 

The PreMiD Chrome extension is also saying that I have an outdated app even though I'm running on the latest version. I've used the Updater app that came with PreMiD multiple times but there was no new update. Weird...

**Comment by austinhuang0131** [comment] 2019-10-18 23:21
Apparently one has to launch PreMiD immediately (like within 10 seconds) after starting Chrome...

**Comment by WOZARDLOZARD** [comment] 2019-10-19 01:10
I tried launching it within the first 10 seconds (pretty sure I did it in 3) and I still got the error. I don't know if you have to allow the app to take control of your computer using accessibility features (which it asks every time after it crashes) but I don't think that's the case...

**Comment by Timeraa** [comment] 2019-10-22 22:23
Huh, what OS did you guys use? Because I am developing on MacOS mainly and it works just fine (the last build was made on Catalina so maybe it could be because of that not sure)

**Comment by WOZARDLOZARD** [comment] 2019-10-27 19:18
PreMiD is now working for me. I had to clean reinstall it by removing the application support folder for it. It was apparently a problem with the config.json file in the application support folder...

**Comment by WOZARDLOZARD** [comment] 2019-10-29 00:08
Update: I tried launching PreMiD again today, and it gave me the same error. I deleted the application support folder for it and it started working. The application support folder for PreMiD reappeared, and when I tested it by closing and reopening the app, it gave me the error. So apparently now it only works if I delete the application support folder every time before I launch the app.

**Comment by Timeraa** [comment] 2020-01-26 05:33
Closing this as I can not reproduce. Try downloading the app from https://premid.app/downloads

**Closed by Timeraa** 2020-01-26 05:33 UTC
