### ISSUE TITLE
Rich presence showing the wrong channel for YouTube

### ISSUE THREAD

**Issue by chaugen1** [PreMiD/PreMiD#213] opened 2019-08-30 23:08 UTC
**Describe the bug**
Displaying in the incorrect channel name of the channel I am watching on YouTube

**To Reproduce**
1. I clicked on a video from my browsing history instead of from the homepage or link.

**Expected behavior**
Show the channel name 'wattles' instead of 'This Is'
**Screenshots**

![image](https://user-images.githubusercontent.com/52175046/64055237-e2899380-cb50-11e9-8bd4-1c801c773e7c.png)
![image](https://user-images.githubusercontent.com/52175046/64055241-e87f7480-cb50-11e9-8d90-a319e9b76600.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome 
 - Version 1.3.2.3

**Additional context**

**Comment by alazymeme** [comment] 2019-08-31 06:36
Can't reproduce based on instructions, works perfectly fine to me when opening from browsing history.
![image](https://user-images.githubusercontent.com/12804673/64060263-76209a00-cc0d-11e9-85db-010d852c24bf.png)
![image](https://user-images.githubusercontent.com/12804673/64060266-7ae54e00-cc0d-11e9-9b6f-9e7a27b278c4.png)

**Comment by chaugen1** [comment] 2019-08-31 15:20
Okay. I'll try and investigate some more. Thanks!

**Comment by Timeraa** [comment] 2019-09-01 10:24
Should be fixed.

**Closed by Timeraa** 2019-09-01 10:24 UTC
