### ISSUE TITLE
Amazon Prime support?

### ISSUE THREAD

**Issue by danielrbickerdike** [PreMiD/PreMiD#163] opened 2019-06-30 17:31 UTC
**Is your feature request related to a problem? Please describe.**
I have switched from Netflix to Amazon Prime

**Describe the solution you'd like**
The same functionality of Netflix RP but with Prime

**Describe alternatives you've considered**
Resubbing to Netflix (but nah)

**Additional context**

**Comment by Timeraa** [comment] 2019-07-06 08:03
Duplicate of [#14](https://github.com/PreMiD/Presences/issues/14)

**Closed by Timeraa** 2019-07-06 08:03 UTC
